services:
  web:
    container_name: web
    restart: always
    build:
      context: app
    ports:
      - '8000:8000'
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
    depends_on:
      - db
    networks:
      - bike_network
  db:
    container_name: db
    restart: always
    image: kartoza/postgis:15
    volumes:
      - ./bike/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - bike_network

networks:
  bike_network:
    name: bike_network
    external: false
